---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos65
    driver:
        box:            learningchef/centos65
        box_url:        learningchef/centos65

suites:
  - name: default
    run_list:
      - recipe[motd-attributes::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
