---
driver:
  name: vagrant
  provider: virtualbox
  vm_hostname: false
  provision: true

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.6.0
  command_prefix: sudo ip netns exec management sudo -u vagrant

verifier:
  command_prefix: sudo ip netns exec management sudo -u vagrant

platforms:
  - name: nexus
    driver:
      box: n9kv
      vagrantfiles:
        - vagrantfiles/nexus.rb

suites:
  - name: default
    run_list:
      - recipe[cisco-test::default]
    attributes:
